export const clubs = [
  {
    id: 'ai',
    logo: '🤖',
    name: 'نادي الذكاء الاصطناعي',
    college: 'كلية الحاسب',
    members: 412,
    events: 18,
    rating: 4.9,
    budget: 48000,
    color: '#6366f1',
    gradient: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
    description: 'نادٍ متخصص في تطوير مهارات الذكاء الاصطناعي وتعلم الآلة',
    achievements: ['المركز الأول هاكاثون السعودية 2025', 'شراكة مع SDAIA'],
    growth: 24.5,
  },
  {
    id: 'theater',
    logo: '🎭',
    name: 'نادي المسرح والفنون',
    college: 'كلية الآداب',
    members: 287,
    events: 14,
    rating: 4.7,
    budget: 32000,
    color: '#a855f7',
    gradient: 'linear-gradient(135deg, #a855f7, #ec4899)',
    description: 'منصة الإبداع المسرحي والفني للطلاب',
    achievements: ['جائزة أفضل عرض مسرحي جامعي'],
    growth: 18.2,
  },
  {
    id: 'sports',
    logo: '⚽',
    name: 'النادي الرياضي',
    college: 'مشترك',
    members: 624,
    events: 22,
    rating: 4.8,
    budget: 75000,
    color: '#10b981',
    gradient: 'linear-gradient(135deg, #10b981, #06b6d4)',
    description: 'بطولات وأنشطة رياضية متنوعة بين الكليات',
    achievements: ['بطولة الجامعات السعودية - كرة قدم', '5 ميداليات ذهبية'],
    growth: 12.8,
  },
  {
    id: 'reading',
    logo: '📚',
    name: 'نادي القراءة',
    college: 'كلية اللغة العربية',
    members: 198,
    events: 9,
    rating: 4.6,
    budget: 18000,
    color: '#f59e0b',
    gradient: 'linear-gradient(135deg, #f59e0b, #fbbf24)',
    description: 'تعزيز ثقافة القراءة وتنظيم اللقاءات الأدبية',
    achievements: ['أكبر معرض كتاب جامعي'],
    growth: 8.4,
  },
  {
    id: 'research',
    logo: '🔬',
    name: 'نادي البحث العلمي',
    college: 'كلية العلوم',
    members: 156,
    events: 12,
    rating: 4.8,
    budget: 42000,
    color: '#06b6d4',
    gradient: 'linear-gradient(135deg, #06b6d4, #3b82f6)',
    description: 'دعم المشاريع البحثية الطلابية ونشر الأبحاث',
    achievements: ['12 ورقة بحثية منشورة', 'منحة بحثية من KACST'],
    growth: 32.1,
  },
  {
    id: 'entrepreneur',
    logo: '🚀',
    name: 'نادي ريادة الأعمال',
    college: 'كلية إدارة الأعمال',
    members: 342,
    events: 16,
    rating: 4.9,
    budget: 58000,
    color: '#ec4899',
    gradient: 'linear-gradient(135deg, #ec4899, #f43f5e)',
    description: 'تمكين رواد الأعمال الطلاب وبناء الشركات الناشئة',
    achievements: ['8 شركات ناشئة', 'تمويل أولي 2 مليون ريال'],
    growth: 41.7,
  },
  {
    id: 'media',
    logo: '🎬',
    name: 'نادي الإعلام الرقمي',
    college: 'كلية الإعلام',
    members: 234,
    events: 13,
    rating: 4.7,
    budget: 36000,
    color: '#f43f5e',
    gradient: 'linear-gradient(135deg, #f43f5e, #f59e0b)',
    description: 'إنتاج المحتوى الإعلامي وتغطية الفعاليات',
    achievements: ['قناة يوتيوب 50K مشترك'],
    growth: 28.3,
  },
  {
    id: 'volunteer',
    logo: '🤝',
    name: 'نادي العمل التطوعي',
    college: 'مشترك',
    members: 478,
    events: 24,
    rating: 4.9,
    budget: 28000,
    color: '#14b8a6',
    gradient: 'linear-gradient(135deg, #14b8a6, #10b981)',
    description: 'مبادرات تطوعية لخدمة المجتمع القصيمي',
    achievements: ['أكثر من 12,000 ساعة تطوع'],
    growth: 22.6,
  },
]

export const events = [
  { id: 1, day: '24', month: 'يونيو', date: '2026-06-24', time: '٩:٠٠ ص', title: 'هاكاثون القصيم للذكاء الاصطناعي', club: 'نادي الذكاء الاصطناعي', location: 'مبنى الحاسب', attendees: 240, capacity: 300, status: 'مفتوح', tag: 'success' },
  { id: 2, day: '27', month: 'يونيو', date: '2026-06-27', time: '٤:٠٠ م', title: 'ملتقى رواد الأعمال الطلابي', club: 'نادي ريادة الأعمال', location: 'قاعة المؤتمرات', attendees: 180, capacity: 250, status: 'تسجيل', tag: 'info' },
  { id: 3, day: '02', month: 'يوليو', date: '2026-07-02', time: '٥:٣٠ م', title: 'بطولة كرة القدم بين الكليات', club: 'النادي الرياضي', location: 'الملعب الرياضي', attendees: 520, capacity: 800, status: 'قريباً', tag: 'warn' },
  { id: 4, day: '08', month: 'يوليو', date: '2026-07-08', time: '٧:٠٠ م', title: 'أمسية شعرية', club: 'نادي القراءة', location: 'مسرح الجامعة', attendees: 95, capacity: 200, status: 'ثقافي', tag: 'violet' },
  { id: 5, day: '12', month: 'يوليو', date: '2026-07-12', time: '٦:٠٠ م', title: 'معرض المشاريع البحثية', club: 'نادي البحث العلمي', location: 'بهو كلية العلوم', attendees: 156, capacity: 200, status: 'علمي', tag: 'info' },
  { id: 6, day: '15', month: 'يوليو', date: '2026-07-15', time: '٨:٠٠ م', title: 'ليلة الإبداع المسرحي', club: 'نادي المسرح والفنون', location: 'المسرح الكبير', attendees: 312, capacity: 400, status: 'فني', tag: 'violet' },
  { id: 7, day: '20', month: 'يوليو', date: '2026-07-20', time: '٤:٣٠ م', title: 'يوم تطوعي - تشجير الحرم', club: 'نادي العمل التطوعي', location: 'الحرم الجامعي', attendees: 218, capacity: 300, status: 'تطوع', tag: 'success' },
  { id: 8, day: '25', month: 'يوليو', date: '2026-07-25', time: '٧:٠٠ م', title: 'ورشة الإنتاج الإعلامي', club: 'نادي الإعلام الرقمي', location: 'استوديو الإعلام', attendees: 78, capacity: 100, status: 'تدريب', tag: 'pink' },
]

export const engagementData = [
  { month: 'يناير', members: 2400, events: 12, satisfaction: 78 },
  { month: 'فبراير', members: 2780, events: 18, satisfaction: 82 },
  { month: 'مارس', members: 3050, events: 22, satisfaction: 85 },
  { month: 'أبريل', members: 3320, events: 19, satisfaction: 83 },
  { month: 'مايو', members: 3680, events: 28, satisfaction: 87 },
  { month: 'يونيو', members: 3980, events: 31, satisfaction: 89 },
  { month: 'يوليو', members: 4150, events: 26, satisfaction: 91 },
  { month: 'أغسطس', members: 4328, events: 37, satisfaction: 93 },
]

export const collegeData = [
  { college: 'الحاسب', members: 624, events: 28 },
  { college: 'الهندسة', members: 512, events: 22 },
  { college: 'الطب', members: 398, events: 14 },
  { college: 'الآداب', members: 471, events: 19 },
  { college: 'العلوم', members: 286, events: 16 },
  { college: 'التربية', members: 342, events: 13 },
  { college: 'إدارة الأعمال', members: 405, events: 21 },
]

export const budgetData = [
  { name: 'الفعاليات', value: 42, color: '#6366f1' },
  { name: 'المسابقات', value: 26, color: '#a855f7' },
  { name: 'التجهيزات', value: 18, color: '#06b6d4' },
  { name: 'التسويق', value: 14, color: '#10b981' },
]

export const radarData = [
  { skill: 'المشاركة', value: 92, full: 100 },
  { skill: 'الإبداع', value: 86, full: 100 },
  { skill: 'القيادة', value: 78, full: 100 },
  { skill: 'الابتكار', value: 88, full: 100 },
  { skill: 'التنظيم', value: 95, full: 100 },
  { skill: 'الأثر', value: 81, full: 100 },
]

export const activityItems = [
  { type: 'join', color: 'var(--accent)', bg: 'var(--accent-soft)', text: 'انضم 18 عضواً جديداً لـ', bold: 'نادي الذكاء الاصطناعي', time: 'قبل 12 دقيقة' },
  { type: 'approve', color: 'var(--emerald)', bg: 'var(--emerald-soft)', text: 'تمت الموافقة على', bold: 'فعالية ملتقى رواد الأعمال', time: 'قبل ساعة' },
  { type: 'award', color: 'var(--gold)', bg: 'var(--gold-soft)', text: 'فاز', bold: 'فريق نادي البرمجة', text2: ' بالمركز الأول', time: 'قبل 3 ساعات' },
  { type: 'request', color: 'var(--cyan)', bg: 'var(--cyan-soft)', text: 'تم تقديم طلب إنشاء', bold: 'نادي ريادة الأعمال الرقمية', time: 'قبل 5 ساعات' },
  { type: 'schedule', color: 'var(--violet)', bg: 'var(--violet-soft)', text: 'تم جدولة', bold: 'بطولة الكليات الرياضية', time: 'أمس' },
]

export const requests = [
  { id: 1, club: 'نادي البلوكشين', college: 'كلية الحاسب', founder: 'م. سلطان الزهراني', members: 28, date: '2026-06-18', status: 'قيد المراجعة', tag: 'warn' },
  { id: 2, club: 'نادي الطيران اللاسلكي', college: 'كلية الهندسة', founder: 'م. عبدالله القحطاني', members: 19, date: '2026-06-16', status: 'موافقة مبدئية', tag: 'info' },
  { id: 3, club: 'نادي الفنون البصرية', college: 'كلية الآداب', founder: 'أ. نورة العتيبي', members: 34, date: '2026-06-14', status: 'معتمد', tag: 'success' },
  { id: 4, club: 'نادي الاستثمار المالي', college: 'إدارة الأعمال', founder: 'أ. ريم الدوسري', members: 41, date: '2026-06-12', status: 'قيد المراجعة', tag: 'warn' },
  { id: 5, club: 'نادي الترفيه الإلكتروني', college: 'مشترك', founder: 'م. خالد المطيري', members: 86, date: '2026-06-10', status: 'مرفوض', tag: 'pink' },
]
